server:
  port: 8081

# Dubbo 广播方式配置
dubbo:
  application:
    name: MyLottery
    version: 1.0.0
  registry:
    address: multicast://224.5.6.7:123451 #N/A
  protocol:
    name: dubbo
    port: 20880