server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123451
    url: jdbc:mysql://127.0.0.1:3307/mylottery?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Dubbo 广播方式配置
dubbo:
  application:
    name: MyLottery
    version: 1.0.0
  registry:
    address:N/A #multicast://224.5.6.7:123451
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.itedus.lottery.rpc